language: node_js
node_js:
  - "node"
jobs:
  include:
    - script: yarn test
      if: branch != master OR tag IS blank
    - stage: publish
      if: tag IS present
      node_js: "node"
      script: yarn build
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        on:
          tags: true
